<<<<<<< HEAD
# Active Spring Profile (Loads application-local.properties for secrets & local environment)
spring.profiles.active=local

# Database Connection (Railway MySQL)
spring.datasource.url=jdbc:mysql://tokaido.proxy.rlwy.net:31012/railway
spring.datasource.username=root
=======
#  Database Connection (Local MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/farmverse

#shared database
#spring.datasource.url=jdbc:mysql://tokaido.proxy.rlwy.net:31012/railway
spring.datasource.username=root
spring.datasource.password=

#shared datbase password
#spring.datasource.password=KxqWXwEpyAzvVwuFgphOiCjFWbAnZjsj
>>>>>>> 474f21004d83522f88edd2aa02f2f287b24ec7ba
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Server & JWT Security
server.port=8080

# JWT Expiration Configuration
jwt.expiration=86400000

# Logging Configuration
logging.level.org.springframework.security=DEBUG
logging.level.com.farmverse=DEBUG

<<<<<<< HEAD
# Google Gemini AI Model Configuration
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# Government Mandi Price API Configuration
mandi.api.key=${MANDI_API_KEY:}
mandi.api.url=https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070
=======
# Google Gemini AI Configuration (API KEY REQUIRED)

spring.ai.google.genai.api-key=your google genai api key
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# Government Mandi Price API

mandi.api.key=your mandi price api key
mandi.api.url=https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=farmverse.app@gmail.com
spring.mail.password=telzgjaqmmznotbd

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
>>>>>>> 474f21004d83522f88edd2aa02f2f287b24ec7ba
